targets:
  $default:
    builders:
      # Typically the builder key is just the package name, run
      # `pub run build_runner doctor` to check your config.
      moor_generator:
        generate_for:
          - lib/src/adapters/sqlite/moor_database.dart
      freezed:
        generate_for:
          - lib/src/models/**.dart