# This is a basic workflow to help you get started with Actions

name: Run Tests(for PRs)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

env:
  flutter_version: "2.2.1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}  
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable 
      
      # Get packages 
      - name: Run pub get   
        run: flutter pub get
      
      # Runs tests for project
      - name: Run tests
        run: flutter test
